<a href="https://colab.research.google.com/github/deraldoduran/APS-Linux/blob/master/TensorflowUsando_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='tensor.png'>

<img src='parcs.png'>

In [22]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [23]:
fashion_mnist = keras.datasets.mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [24]:
train_images.shape

(60000, 28, 28)

In [25]:
len(train_labels)

60000

In [26]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [27]:
test_images.shape

(10000, 28, 28)

In [28]:
len(test_labels)

10000

In [29]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [30]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [31]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(50, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                510       
Total params: 39,760
Trainable params: 39,760
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [33]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5223 - accuracy: 0.8544
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1680 - accuracy: 0.9516
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1202 - accuracy: 0.9638
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0928 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0789 - accuracy: 0.9761


In [34]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 1ms/step - loss: 0.1009 - accuracy: 0.9700
Test accuracy: 0.9700000286102295


In [35]:
predictions = model.predict(test_images)

In [36]:
predictions[0]

array([5.5449993e-07, 1.2172932e-09, 1.1337011e-05, 7.3128482e-05,
       3.2213127e-10, 1.5266697e-06, 1.2792398e-10, 9.9990642e-01,
       2.1890944e-06, 4.7677026e-06], dtype=float32)

In [37]:
np.argmax(predictions[0])

7

In [38]:
test_labels[0]

7

In [39]:
img = test_images[0]

print(img.shape)

(28, 28)


In [40]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [41]:
predictions_single = model.predict(img)

print(predictions_single)

[[5.5449993e-07 1.2172932e-09 1.1337011e-05 7.3128409e-05 3.2213127e-10
  1.5266668e-06 1.2792398e-10 9.9990642e-01 2.1890964e-06 4.7677072e-06]]


In [42]:
np.argmax(predictions_single[0])

7